apiVersion: apps/v1
kind: deployment
metadata:
  labels:
    name: Housing-price-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      labels:
        app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor-api
        image:
        ports:
        - containerPort:8000
# we can use kubectl set image to change name of image so that newly built images can be feed to deployment file
# kubectl set image deployment/deployment-name container-name=new-container-image:latest
